[local]
# Set a path to your root EarthCARE data directory,
# where local EarthCARE product files will be searched and downloaded to.
data_directory = "/content/drive/MyDrive/Colab Notebooks/earth-care-amazon-2025/data"

# Set a path to your root image directory,
# where saved plots will be put.
image_directory = "/content/drive/MyDrive/Colab Notebooks/earth-care-amazon-2025/outputs/figures"

# Optionally, customize the sub-folder structure used in your data directory
[local.data_directory_structure]
subdir_template = "{level}/{file_type}/{year}/{month}/{day}/{baseline}"
subdir_name_auxiliary_files = "auxiliary_files"
subdir_name_orbit_files = "orbit_files"
subdir_name_level0 = "level0"
subdir_name_level1b = "level1b"
subdir_name_level1c = "level1c"
subdir_name_level2a = "level2a"
subdir_name_level2b = "level2b"

[download]
# You have 2 options to set your data access rights:
# 1. (recommended) Choose one: "commissioning", "calval" or "open", e.g.:
#         collections = "calval"
# 2. List individual collections, e.g.:
#         collections = [
#             "EarthCAREL1InstChecked",
#             "EarthCAREL2InstChecked",
#             ...
#         ]
collections = "open"

# Set your data dissemination service that will be used for remote data search and download.
# Choose one: "oads" or "maap"
platform = "maap"

# If you've choosen "maap", generate a data access token on EarthCARE MAAP and put it here:
# (see <https://portal.maap.eo.esa.int/ini/services/auth/token/>)
maap_token = "eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjOTVmMGU4My02YjZkLTQ2YjEtOWJjZi1kZGUzZDdiOTY3N2QifQ.eyJleHAiOjE3NzM3MDk1MzEsImlhdCI6MTc2NTg0NzEzMSwianRpIjoiMDIzODY3ZTAtNDg5ZS00MWJmLTk1OGItNDY0MTY2NGEwMTFjIiwiaXNzIjoiaHR0cHM6Ly9pYW0ubWFhcC5lby5lc2EuaW50L3JlYWxtcy9lc2EtbWFhcCIsImF1ZCI6Imh0dHBzOi8vaWFtLm1hYXAuZW8uZXNhLmludC9yZWFsbXMvZXNhLW1hYXAiLCJzdWIiOiIyOGQ5ZmMzZC04ZmZmLTRiMWUtOWQ2ZC05MmQyYjViOWU5NTkiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoib2ZmbGluZS10b2tlbiIsInNpZCI6ImY4YWQ3M2E5LWJjNGEtNGZkYi1iNWVmLWU4ZmRkMTIzYmRjMiIsInNjb3BlIjoib3BlbmlkIEVTQS1NQUFQLUZlZGVyYXRlU291cmNlcyBFU0EtTUFBUC1BdXRob3JpemF0aW9uIEVTQV9NQUFQX1N0YXRpc3RpY3MgcHJvZmlsZSBvZmZsaW5lX2FjY2VzcyBFU0EtTUFBUC1QQUxOZXh0Q2xvdWQifQ.vn5kICWTLm5XshPap9WE4TLsAf6aiBUwgF5DKYflizdYfzc3gVCGJ7WWnE_0MkftdKFOrkjmS495EAtsbyxQ5Q"

# Using MAAP you can speed up the download by only downloading the .h5-file excluding the related header file .HDR. maap_include_header_file = false

# If you've choosen "oads", give your OADS credencials here:
# (see <https://ec-pdgs-dissemination1.eo.esa.int> and <https://ec-pdgs-dissemination2.eo.esa.int>)
# oads_username = "my_username"
# oads_password = """my_password"""
